services:
  todoapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-api
    ports:
      - "3087:3087"
    environment:
      - ASPNETCORE_URLS=http://+:3087
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=todo_db;Username=postgres;Password=postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    container_name: todo-postgres
    restart: always
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: